### ISSUE TITLE
cannot open abide.hdf5

### ISSUE THREAD

**Issue by X-funbean** [OPTML-Group/ILM-VP#3]
Hi, I tried to run the training codes. The training was smooth excpet for the ABIDE dataset. The dataset was successfully downloaded:

![image](https://github.com/OPTML-Group/ILM-VP/assets/24663255/5d1b090e-a7c3-446b-ab4f-e3235482c9d8)

but an issue was raised when reading the abide.hdf5 file: 
`"Unable to open object (file read failed: time = Mon Oct  9 10:52:03 2023\n, filename = '/root/xfb/datasets/prompt/abide/abide.hdf5', file descriptor = 24, errno = 5, error message = 'Input/output error', buf = 0x7775b70, total read size = 512, bytes this sub-read = 512, bytes actually read = 18446744073709551615, offset = 0)"`

I tried to re-downloaded the file several times, but the issue remained. I'm using lmdb-1.4.1 and h5py-3.9.0. What could be the reason for this? Please help me out. Thx!

**Comment by Phoveran** [comment]
Sorry for seeing this so late. You might have solved the problem? If not, could you try abide.hdf5 file from [here](https://github.com/lsa-pucrs/acerta-abide)?

**Comment by Phoveran** [comment]
Closed for no response. Reopen if still needs.
